import mods.recipestages.Recipes;
import mods.ItemStages;
import crafttweaker.item.IItemStack;
import crafttweaker.item.IItemCondition;

recipes.remove(<minecraft:gunpowder>);
recipes.remove(<techguns:itemshared:57>);

mods.techguns.ChemLab.removeRecipe(<minecraft:gunpowder>,null);
mods.techguns.ChemLab.removeRecipe(<techguns:itemshared:96>,null);
mods.techguns.ChemLab.addRecipe(<minecraft:coal>,1,<minecraft:coal>,1,<liquid:oil>*1000,false,<techguns:itemshared:96>,<liquid:water>*0,25);

mods.mekanism.enrichment.removeRecipe(<ore:dustSulfur>);
mods.mekanism.enrichment.removeRecipe(<ore:dustSaltpeter>);
mods.mekanism.crusher.removeRecipe(<minecraft:gunpowder>);

Recipes.addShaped("military_stage", <photoptics:handheldtelescope_diamondgreen>, [[null, <minecraft:stained_glass_pane:5>, null],[null, <minecraft:diamond_block>, null], [null, <ore:circuitBasic>, null]]);
Recipes.addShaped("military_stage", <photoptics:handheldtelescope_diamondred>, [[null, <minecraft:stained_glass_pane:14>, null],[null, <minecraft:diamond_block>, null], [null, <ore:circuitBasic>, null]]);
Recipes.addShaped("military_stage", <photoptics:handheldtelescope_diamondblue>, [[null, <minecraft:stained_glass_pane:3>, null],[null, <minecraft:diamond_block>, null], [null, <ore:circuitBasic>, null]]);
Recipes.addShaped("military_stage", <photoptics:binoculars_diamondgreen>, [[<minecraft:stained_glass_pane:5>, <ore:circuitBasic>, <minecraft:stained_glass_pane:5>],[<minecraft:diamond>, <ore:ingotSteel>, <minecraft:diamond>], [<minecraft:stained_glass_pane:5>, null, <minecraft:stained_glass_pane:5>]]);
Recipes.addShaped("military_stage", <photoptics:binoculars_diamondred>, [[<minecraft:stained_glass_pane:14>, <ore:circuitBasic>, <minecraft:stained_glass_pane:14>],[<minecraft:diamond>, <ore:ingotSteel>, <minecraft:diamond>], [<minecraft:stained_glass_pane:14>, null, <minecraft:stained_glass_pane:14>]]);
Recipes.addShaped("military_stage", <photoptics:binoculars_diamondblue>, [[<minecraft:stained_glass_pane:3>, <ore:circuitBasic>, <minecraft:stained_glass_pane:3>],[<minecraft:diamond>, <ore:ingotSteel>, <minecraft:diamond>], [<minecraft:stained_glass_pane:3>, null, <minecraft:stained_glass_pane:3>]]);
Recipes.addShaped("military_stage", <techguns:itemshared:5>, [[<ore:plateIron>, null, <ore:plateIron>],[<ore:plateIron>, <minecraft:tnt>, <ore:plateIron>], [<ore:plateIron>, null, <ore:plateIron>]]);

val stageItems as IItemStack[] = [
    <techguns:item_door3x3:1>,
    <techguns:item_door3x3:2>,
    <techguns:item_door3x3>,
    <techguns:item_door3x3:3>,
    <techguns:itemshared:133>,
    <techguns:itemshared:132>,
    <techguns:itemshared:14>,
    <techguns:itemshared:12>,
    <techguns:itemshared:11>,
    <techguns:itemshared:13>,
    <techguns:itemshared:35>,
    <techguns:itemshared:43>,
    <techguns:itemshared:44>,
    <techguns:itemshared:72>,
    <techguns:combatknife>,
    <techguns:itemshared:4>,
    <techguns:itemshared:5>,
    <techguns:itemshared:7>,
    <techguns:riot_shield>,
    <techguns:stielgranate>,
    <techguns:fraggrenade>,
    <techguns:itemshared:8>,
    <techguns:t2_beret>,
    <techguns:simplemachine:8>,
    <techguns:basicmachine:2>,
    <techguns:simplemachine:9>,
    <techguns:simplemachine:10>,
    <techguns:simplemachine2:8>,
    <techguns:nethermetal:6>,
    <techguns:nethermetal:7>,
    <techguns:nethermetal:8>,
    <techguns:nethermetal:9>,
    <techguns:concrete>,
    <techguns:concrete:1>,
    <techguns:concrete:2>,
    <techguns:concrete:3>,
    <techguns:nethermetal:5>,
    <techguns:metalpanel:4>,
    <techguns:metalpanel:5>,
    <techguns:metalpanel:6>,
    <techguns:metalpanel:7>,
    <techguns:nethermetal>,
    <techguns:nethermetal:1>,
    <techguns:nethermetal:2>,
    <techguns:nethermetal:3>,
    <techguns:metalpanel:3>,
    <techguns:sandbags>,
    <techguns:item_bunkerdoor>,
    <techguns:lamp0>,
    <techguns:lamp0:6>,
    <techguns:lamp0:12>,
    <techguns:lamp0:13>,
    <techguns:metalpanel>,
    <techguns:metalpanel:1>,
    <techguns:metalpanel:2>,
    <techguns:t2_commando_helmet>,
    <techguns:t2_commando_chestplate>,
    <techguns:t2_commando_leggings>,
    <techguns:t2_commando_boots>,
    <techguns:t2_combat_helmet>,
    <techguns:t2_combat_chestplate>,
    <techguns:t2_combat_leggings>,
    <techguns:t2_combat_boots>,
    <techguns:itemshared:56>,
    <techguns:military_crate:6>,
    <techguns:military_crate:7>,
    <techguns:military_crate:8>,
    <techguns:explosive_charge>,
    <techguns:explosive_charge:1>,
    <techguns:itemshared:34>,
    <techguns:neonlights:2>,
    <techguns:neonlights:3>,
    <techguns:neonlights:4>,
    <techguns:military_crate>,
    <techguns:military_crate:1>,
    <techguns:military_crate:2>,
    <techguns:military_crate:4>,
    <techguns:military_crate:3>,
    <techguns:military_crate:5>,
    <techguns:camonet_top>,
    <techguns:camonet_top:1>,
    <techguns:camonet_top:2>,
    <techguns:stairs_metal:7>,
    <techguns:stairs_metal:15>,
    <techguns:stairs_concrete:7>,
    <techguns:stairs_concrete:15>,
    <techguns:neonlights>,
    <techguns:neonlights:1>,
    <techguns:concrete:4>,
    <techguns:concrete:5>,
    <techguns:ladder0:8>,
    <techguns:ladder0:9>,
    <techguns:ladder0:10>,
    <techguns:ladder0:11>,
    <techguns:camonet>,
    <techguns:camonet:1>,
    <techguns:camonet:2>,
    <techguns:itemshared:89>,
    <techguns:radaway>,
    <techguns:radpills>,
    <techguns:gasmask>,
    <techguns:itemshared:147>,
    <techguns:itemshared:148>,
    <techguns:itemshared:149>,
    <techguns:itemshared:150>,
    <techguns:itemshared:151>,
    <techguns:itemshared:152>,
    <techguns:itemshared:58>,
    <techguns:itemshared:55>,
    <techguns:itemshared:46>,
    <techguns:itemshared:47>,
    <techguns:itemshared:48>,
    <techguns:itemshared:49>,
    <techguns:itemshared:50>,
    <techguns:itemshared:51>,
    <techguns:itemshared:52>,
    <techguns:itemshared:54>,
    <techguns:simplemachine2:9>,
    <techguns:itemshared:15>,
    <techguns:itemshared:16>,
    <techguns:ballistic_shield>,
    <techguns:advanced_shield>,
    <techguns:itemshared:23>,
    <techguns:itemshared:24>,
    <techguns:itemshared:27>,
    <techguns:itemshared:28>,
    <techguns:itemshared:95>,
    <techguns:itemshared:96>,
    <techguns:itemshared:103>,
    <techguns:scubatanks>,
    <techguns:itemshared:93>,
    <techguns:itemshared:146>
];

val techGuns as IItemStack[] = [
    <techguns:combatshotgun>,
    <techguns:mac10>,
    <techguns:aug>,
    <techguns:flamethrower>,
    <techguns:ak47>,
    <techguns:m4>,
    <techguns:pistol>,
    <techguns:lmg>
];

val techGunRecipes as string[] = [
    "techguns:combatshotgun",
    "techguns:mac10_alt",
    "techguns:aug_alt",
    "techguns:flamethrower_alt",
    "techguns:ak47_alt",
    "techguns:m4_alt",
    "techguns:pistol_alt",
    "techguns:lmg_alt"
];

val vehicles as IItemStack[] = [
    <mts:unumilitary.unumilitary_trailer_unu_mule_cargo_wintercamo>,
    <mts:unumilitary.unumilitary_trailer_unu_wolf_generator_desert>,
    <mts:unumilitary.unumilitary_trailer_unu_wolf_generator_desertcamo>,
    <mts:unumilitary.unumilitary_trailer_unu_wolf_generator_forrest>,
    <mts:unumilitary.unumilitary_trailer_unu_wolf_generator_forrestcamo>,
    <mts:unumilitary.unumilitary_trailer_unu_wolf_generator_winter>,
    <mts:unumilitary.unumilitary_trailer_unu_wolf_generator_wintercamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_ferret_desert>,
    <mts:unumilitary.unumilitary_vehicle_unu_ferret_forrest>,
    <mts:unumilitary.unumilitary_plane_unu_aurornis>,
    <mts:unumilitary.unumilitary_plane_unu_navigator_cargo_ang>,
    <mts:unumilitary.unumilitary_plane_unu_navigator_cargo_blackthorne>,
    <mts:unumilitary.unumilitary_plane_unu_navigator_cargo_orange>,
    <mts:unumilitary.unumilitary_trailer_unu_mule_cargo_desert>,
    <mts:unumilitary.unumilitary_trailer_unu_mule_cargo_desertcamo>,
    <mts:unumilitary.unumilitary_trailer_unu_mule_cargo_forrest>,
    <mts:unumilitary.unumilitary_trailer_unu_mule_cargo_forrestcamo>,
    <mts:unumilitary.unumilitary_trailer_unu_mule_cargo_winter>,
    <mts:unumilitary.unumilitary_boat_unu_salmon_winter>,
    <mts:unumilitary.unumilitary_boat_unu_salmon_wintercamo>,
    <mts:unumilitary.unumilitary_heli_unu_crow_blackthorne>,
    <mts:unumilitary.unumilitary_heli_unu_crow_desert>,
    <mts:unumilitary.unumilitary_heli_unu_crow_desertcamo>,
    <mts:unumilitary.unumilitary_heli_unu_crow_forrest>,
    <mts:unumilitary.unumilitary_heli_unu_crow_forrestcamo>,
    <mts:unumilitary.unumilitary_heli_unu_crow_winter>,
    <mts:unumilitary.unumilitary_heli_unu_crow_wintercamo>,
    <mts:unumilitary.unumilitary_aagun_unu_cicada_desert>,
    <mts:unumilitary.unumilitary_aagun_unu_cicada_forrest>,
    <mts:unumilitary.unumilitary_aagun_unu_cicada_winter>,
    <mts:unumilitary.unumilitary_airship_unu_aerwhale>,
    <mts:unumilitary.unumilitary_boat_unu_dingy>,
    <mts:unumilitary.unumilitary_boat_unu_salmon_desert>,
    <mts:unumilitary.unumilitary_boat_unu_salmon_desertcamo>,
    <mts:unumilitary.unumilitary_boat_unu_salmon_forrest>,
    <mts:unumilitary.unumilitary_boat_unu_salmon_forrestcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_base_desertcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_base_forrest>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_base_forrestcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_base_winter>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_base_wintercamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_halftrack_wintercamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_pantherx>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_amphibious_desert>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_amphibious_desertcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_amphibious_forrest>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_amphibious_forrestcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_amphibious_winter>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_amphibious_wintercamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_wolf_base_desert>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_base_forrest>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_base_forrestcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_base_winter>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_base_wintercamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_halftrack_desert>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_halftrack_desertcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_halftrack_forrest>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_halftrack_forrestcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_halftrack_winter>,
    <mts:unumilitary.unumilitary_vehicle_unu_ferret_winter>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_amphibious_desert>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_amphibious_desertcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_amphibious_forrest>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_amphibious_forrestcamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_amphibious_winter>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_amphibious_wintercamo>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_base_desert>,
    <mts:unumilitary.unumilitary_vehicle_unu_mule_base_desertcamo>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_attattention>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_attattention_desert>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_attattention_forrest>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_attattention_winter>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_behindblock>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_behindblock_desert>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_behindblock_forrest>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_behindblock_winter>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_lying>,
    <mts:unumilitary.unumilitary_ammo_unu_ammo_0300mmflak>,
    <mts:unumilitary.unumilitary_ammo_unu_ammo_1000mmrailgun>,
    <mts:unumilitary.unumilitary_ammo_unu_bomb_2500mm>,
    <mts:unuparts.unuparts_part_unu_wheel_standard_offroad_desert>,
    <mts:unuparts.unuparts_part_unu_wheel_standard_offroad_forrest>,
    <mts:unuparts.unuparts_part_unu_wheel_standard_offroad_winter>,
    <mts:unuparts.unuparts_part_unu_wheel_truck_budd_desert>,
    <mts:unuparts.unuparts_part_unu_wheel_truck_budd_forrest>,
    <mts:unuparts.unuparts_part_unu_wheel_truck_budd_winter>,
    <mts:unumilitary.unumilitary_gun_unu_m50cal>,
    <mts:unumilitary.unumilitary_gun_unu_mosquito>,
    <mts:unumilitary.unumilitary_gun_unu_rifle1>,
    <mts:unumilitary.unumilitary_gun_unu_stinger>,
    <mts:unumilitary.unumilitary_gun_unu_turret_dualm50cal>,
    <mts:unumilitary.unumilitary_part_unu_barrel_cicada>,
    <mts:unumilitary.unumilitary_part_unu_turret_pantherx>,
    <mts:unumilitary.unumilitary_ammo_unu_ammo_0055mm>,
    <mts:unumilitary.unumilitary_ammo_unu_ammo_0127mm>,
    <mts:unumilitary.unumilitary_part_unu_crate_24_desert>,
    <mts:unumilitary.unumilitary_part_unu_crate_24_forrest>,
    <mts:unumilitary.unumilitary_part_unu_crate_24_winter>,
    <mts:unumilitary.unumilitary_part_unu_crate_6_desert>,
    <mts:unumilitary.unumilitary_part_unu_crate_6_forrest>,
    <mts:unumilitary.unumilitary_part_unu_crate_6_winter>,
    <mts:unumilitary.unumilitary_gun_unu_locust>,
    <mts:unumilitary.unumilitary_gun_unu_locustlong>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_lying_desert>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_lying_forrest>,
    <mts:unumilitary.unumilitary_decor_blackthorne_soldier_lying_winter>,
    <mts:unuparts.unuparts_part_steve_blackthornesoldier>,
    <mts:unuparts.unuparts_part_steve_blackthornesoldier_desert>,
    <mts:unuparts.unuparts_part_steve_blackthornesoldier_forrest>,
    <mts:unuparts.unuparts_part_steve_blackthornesoldier_winter>
];

for item in stageItems {
    Recipes.setRecipeStage("military_stage", item);
    ItemStages.addItemStage("military_stage", item);
}

for item in techGuns {
    Recipes.setRecipeStage("military_stage", item);
    ItemStages.addItemStage("military_stage", item);
}

for recipe in techGunRecipes{
    Recipes.setRecipeStage("military_stage", recipe);
}

for item in vehicles {
    ItemStages.addItemStage("military_stage", item);
}