#priority 1
// This script contains all the gamestages that we use throughout the entire progression. Make all changes to this array, which get's crossed referenced to our other scripts.

// Make sure to keep this updated!!

static gameStages as string[] = [
    // Tier 1 Techs:
    "advanced_redstone_tech",
    "advanced_tools_tech",
    "architecture_tech",
    "basic_tools_tech", 
    "cartography_tech",
    "cooking_tech",
    "iron_tech",
    // Tier 2 Techs:
    "advanced_military_tech",
    "basic_circuitry_tech",
    "basic_engineering_tech",
    "basic_military_tech",
    "blacksmithing_tech",
    "kitchen_tech",
    "oil_processing_tech",
    "pollution_management_tech",
    "replaceable_parts_tech",
    "sailing_tech",
    // Steel Techs:
    "arc_smelting_tech",
    "biodiesel_tech",
    "electricity_tech",
    "fluidynamics_tech",
    "heavy_machinery_tech",
    "logistics_tech",
    "railroading_tech",
    "steam_energy_tech",
    "steel_tech",
    "thermodynamics_tech",
    // Tier 3
    "advanced_compact_machinery_tech",    
    "aeromobiles_tech",
    "mechanics_tech",
    "chemical_synthesis_tech",
    "compact_machinery_tech",
    "computer_tech",
    "future_tech",
    "scientific_theory_tech",
    "server_storage_tech",
    "solar_tech",
    "wireless_tech",
    // Military Techs
    "basic_missiles_tech",
    "intercontinental_ballistics_tech",
    "manhattan_project_tech",
    "modern_military_tech",
    // Nuclear Techs
    "atomic_theory_tech",
    "fission_reactors_tech",
    "fusion_reactors_tech",
    // Space Techs
    "asteroid_mining_tech",
    "basic_rocketry_tech",
    "space_exploration_tech",
    "space_stations_tech",
    "warp_tech",
    // Specializations:
    "agriculture_spec",
    "agriculture_tech_spec",
    "forestry_spec",
    "forestry_tech_spec",
    "mining_spec",
    "mining_tech_spec",
    "composite_construction_spec",
    "composite_construction_tech_spec",
    "electrical_distribution_spec",
    "electrical_distribution_tech_spec",
    "industrial_manufacturing_spec",
    "industrial_manufacturing_tech_spec",
    "chemical_engineering_spec",
    "chemical_engineering_tech_spec",
    "electrical_engineering_spec",
    "electrical_engineering_tech_spec",
    "mechanical_engineering_spec",
    "mechanical_engineering_tech_spec",
    "nuclear_engineering_spec",
    "nuclear_engineering_tech_spec"
];