import mods.ItemStages;
import mods.recipestages.Recipes;
import crafttweaker.item.IItemStack;


/** 
    ## Deleted Items ##

    Industrial Renewal Items - Many don't fit, or are present in other mods that should be used instead
    Destruction Tool - Can easy destroy other's stuff, the master griefing tool
    Techguns Blast Furnace - Using the IE blastfurnace
    Guages and Switches Glass Stuff - Glass switches and such didn't seem like it actually made since, and didn't really fit in any techs
    Advanced Rocketry Items - Other machines do the same thing, or some items don't fit
    ICBM Items - 

*/

val disabledItems as IItemStack[] = [
    <buildinggadgets:destructiontool>,
    <immersiveengineering:metal_device1:3>,
    <techguns:simplemachine:11>,
    <techguns:basicmachine:1>,
    <techguns:orecluster:6>,
    <techguns:orecluster:7>,
    <techguns:orecluster:8>,
    <techguns:oredrill>,
    <techguns:oredrill:1>,
    <techguns:oredrill:2>,
    <techguns:oredrill:3>,
    <techguns:oredrill:4>,
    <techguns:sand_hard>,
    <techguns:slimy>,
    <techguns:slimyladder:3>,
    <techguns:orecluster>,
    <techguns:orecluster:1>,
    <techguns:orecluster:2>,
    <techguns:orecluster:3>,
    <techguns:orecluster:4>,
    <techguns:orecluster:5>,
    <techguns:tg_spawner>,
    <techguns:tg_spawner:1>,
    <techguns:nethermetal:4>,
    <techguns:bioblob>,
    <techguns:itemshared:66>,
    <techguns:glider>,
    <techguns:itemshared:90>,
    <techguns:itemshared:91>,
    <techguns:itemshared:134>,
    <techguns:itemshared:135>,
    <techguns:itemshared:136>,
    <techguns:itemshared:137>,
    <techguns:itemshared:138>,
    <techguns:itemshared:139>,
    <techguns:itemshared:140>,
    <techguns:itemshared:141>,
    <techguns:itemshared:142>,
    <rsgauges:sensitiveglass_black>,
    <rsgauges:sensitiveglass_inverted>,
    <rsgauges:sensitiveglass_magenta>,
    <rsgauges:sensitiveglass_lightblue>,
    <rsgauges:sensitiveglass_lime>,
    <rsgauges:sensitiveglass_pink>,
    <rsgauges:sensitiveglass_gray>,
    <rsgauges:sensitiveglass_lightgray>,
    <rsgauges:sensitiveglass_cyan>,
    <rsgauges:sensitiveglass_purple>,
    <rsgauges:sensitiveglass_brown>,
    <rsgauges:detectorswitch_glass1>,
    <rsgauges:detectorswitch_glass2>,
    <rsgauges:sensitiveglass>,
    <rsgauges:sensitiveglass_white>,
    <rsgauges:sensitiveglass_red>,
    <rsgauges:sensitiveglass_green>,
    <rsgauges:sensitiveglass_blue>,
    <rsgauges:sensitiveglass_yellow>,
    <rsgauges:sensitiveglass_orange>,
    <rsgauges:bistableswitch_glass1>,
    <rsgauges:bistableswitch_glass2>,
    <rsgauges:pulseswitch_glass1>,
    <rsgauges:pulseswitch_glass2>,
    <rsgauges:pulseswitch_glass3>,
    <rsgauges:contactmat_glass1>,
    <rsgauges:contactmat_glass2>,
    <rsgauges:daytimeswitch_glass1>,
    <rsgauges:timerswitch_glass1>,
    <rsgauges:powerplant_red>,
    <rsgauges:powerplant_yellow>,
    <advancedrocketry:platepress>,
    <advancedrocketry:electrolyser>,
    <advancedrocketry:crystallizer>,
    <advancedrocketry:bipropellantrocketmotor>,
    <advancedrocketry:advbipropellantrocketmotor>,
    <advancedrocketry:bipropellantfueltank>,
    <advancedrocketry:oxidizerfueltank>,
    <advancedrocketry:nuclearcore>,
    <advancedrocketry:nuclearrocketmotor>,
    <advancedrocketry:nuclearfueltank>,
    <advancedrocketry:itemupgrade:2>,
    <advancedrocketry:itemupgrade:1>,
    <advancedrocketry:basiclasergun>,
    <advancedrocketry:jackhammer>,
    <advancedrocketry:misc:1>,
    <thermalfoundation:tome_lexicon>,
    <thermalfoundation:tool.hammer_copper>,
    <thermalfoundation:tool.hammer_tin>,
    <thermalfoundation:tool.hammer_silver>,
    <thermalfoundation:tool.hammer_lead>,
    <thermalfoundation:tool.hammer_aluminum>,
    <thermalfoundation:tool.hammer_nickel>,
    <thermalfoundation:tool.hammer_platinum>,
    <thermalfoundation:tool.hammer_steel>,
    <thermalfoundation:tool.hammer_electrum>,
    <thermalfoundation:tool.hammer_invar>,
    <thermalfoundation:tool.hammer_bronze>,
    <thermalfoundation:tool.hammer_constantan>,
    <thermalfoundation:tool.hammer_iron>,
    <thermalfoundation:tool.hammer_diamond>,
    <thermalfoundation:tool.hammer_gold>,
    <thermalfoundation:tool.excavator_invar>,
    <thermalfoundation:tool.excavator_bronze>,
    <thermalfoundation:tool.excavator_constantan>,
    <thermalfoundation:tool.excavator_iron>,
    <thermalfoundation:tool.excavator_diamond>,
    <thermalfoundation:tool.excavator_gold>,
    <thermalfoundation:tool.excavator_tin>,
    <thermalfoundation:tool.excavator_silver>,
    <thermalfoundation:tool.excavator_lead>,
    <thermalfoundation:tool.excavator_electrum>,
    <thermalfoundation:tool.excavator_steel>,
    <thermalfoundation:tool.excavator_platinum>,
    <thermalfoundation:tool.excavator_nickel>,
    <thermalfoundation:tool.excavator_aluminum>,
    <thermalfoundation:tool.excavator_copper>,
    <icbmclassic:signaldisrupter>,
    <icbmclassic:clump>,
    <icbmclassic:wire>,
    <icbmclassic:ingot:1>,
    <icbmclassic:ingot>,
    <storagedrawers:tape>,
    <locks:wood_lock_pick>,
    <appliedenergistics2:network_tool>,
    <appliedenergistics2:material:6>,
    <industrialwires:ic2_connector>,
    <industrialwires:ic2_connector:1>,
    <industrialwires:ic2_connector:2>,
    <industrialwires:ic2_connector:3>,
    <industrialwires:ic2_connector:4>,
    <industrialwires:ic2_connector:5>,
    <industrialwires:ic2_connector:6>,
    <industrialwires:ic2_connector:7>,
    <industrialwires:ic2_wire_coil>,
    <industrialwires:ic2_wire_coil:1>,
    <industrialwires:ic2_wire_coil:2>,
    <industrialwires:ic2_wire_coil:3>,
    <industrialwires:ic2_wire_coil:4>,
    <industrialwires:ic2_wire_coil:5>,
    <industrialwires:ic2_wire_coil:6>,
    <industrialwires:ic2_wire_coil:7>,
    <industrialwires:ic2_connector:8>,
    <industrialwires:ic2_connector:9>,
    <mekanismgenerators:reactor>,
    <mekanismgenerators:reactor:1>,
    <mekanismgenerators:reactor:2>,
    <mekanismgenerators:reactor:3>,
    <mekanismgenerators:reactorglass>,
    //Everything below are items temporarily disabled since they bypass explosion restrictions, until I figure out a solution
    <icbmclassic:grenade:2>,
    <icbmclassic:explosives:2>,
    <icbmclassic:missile:2>,
    <icbmclassic:missile:8>,
    <icbmclassic:missile:9>,
    <icbmclassic:missile:10>,
    <icbmclassic:missile:11>,
    <icbmclassic:missile:12>,
    <icbmclassic:missile:13>,
    <icbmclassic:explosives:8>,
    <icbmclassic:explosives:9>,
    <icbmclassic:explosives:10>,
    <icbmclassic:explosives:11>,
    <icbmclassic:explosives:12>,
    <icbmclassic:explosives:13>,
    <icbmclassic:explosives:14>,
    <icbmclassic:missile:17>,
    <icbmclassic:missile:20>,
    <icbmclassic:missile:16>,
    <icbmclassic:missile:18>,
    <icbmclassic:missile:19>,
    <icbmclassic:missile:15>,
    <icbmclassic:missile:21>,
    <icbmclassic:missile:22>,
    <icbmclassic:missile:23>,
    <icbmclassic:explosives:17>,
    <icbmclassic:explosives:20>,
    <icbmclassic:explosives:16>,
    <icbmclassic:explosives:18>,
    <icbmclassic:explosives:19>,
    <icbmclassic:explosives:15>,
    <icbmclassic:explosives:21>,
    <icbmclassic:explosives:22>,
    <icbmclassic:explosives:23>,
    <icbmclassic:bombcart:10>,
    <icbmclassic:bombcart:8>,
    <icbmclassic:bombcart:11>,
    <icbmclassic:bombcart:13>,
    <icbmclassic:bombcart:9>,
    <icbmclassic:bombcart:22>,
    <icbmclassic:bombcart:23>,
    <icbmclassic:explosives:22>,
    <icbmclassic:explosives:23>,
    <icbmclassic:bombcart:17>,
    <icbmclassic:bombcart:20>,
    <icbmclassic:bombcart:16>,
    <icbmclassic:bombcart:18>,
    <icbmclassic:bombcart:15>,
    <icbmclassic:bombcart:19>,
    <icbmclassic:bombcart:21>,
    <icbmclassic:bombcart:2>
    // End
];

for item in disabledItems {
    Recipes.setRecipeStage("disabled", item);
    ItemStages.addItemStage("disabled", item);
}