import mods.ItemStages;
import mods.recipestages.Recipes;
import crafttweaker.item.IItemStack;
import mods.nuclearcraft.chemical_reactor;
import mods.nuclearcraft.electrolyser;

/**
    Fission Reactors:
    Unlocks everything to create fission reactors
*/

// Stage Name
val stage = "fission_reactors_tech";

val stageMods as string[] = [

];

val stageItems as IItemStack[] = [
    // Davincis Vessels Balloons because you technically can't get them until here
    <davincisvessels:balloon:15>,
    <davincisvessels:balloon:6>,
    <davincisvessels:balloon:7>,
    <davincisvessels:balloon:8>,
    <davincisvessels:balloon:9>,
    <davincisvessels:balloon:10>,
    <davincisvessels:balloon:11>,
    <davincisvessels:balloon:12>,
    <davincisvessels:balloon:13>,
    <davincisvessels:balloon:14>,
    <davincisvessels:balloon>,
    <davincisvessels:balloon:1>,
    <davincisvessels:balloon:2>,
    <davincisvessels:balloon:3>,
    <davincisvessels:balloon:4>,
    <davincisvessels:balloon:5>,
    <nuclearcraft:fuel_reprocessor_idle>,
    <nuclearcraft:isotope_separator_idle>,
    <nuclearcraft:decay_hastener_idle>,
    <nuclearcraft:infuser_idle>,
    <nuclearcraft:melter_idle>,
    <nuclearcraft:salt_mixer_idle>,
    <nuclearcraft:crystallizer_idle>,
    <nuclearcraft:extractor_idle>,
    <nuclearcraft:centrifuge_idle>,
    <nuclearcraft:rock_crusher_idle>,
    <nuclearcraft:reactor_casing_transparent>,
    <nuclearcraft:cell_block>,
    <nuclearcraft:reactor_trapdoor>,
    <nuclearcraft:fission_controller_new_fixed>,
    <nuclearcraft:fission_port>,
    <nuclearcraft:fission_block>,
    <nuclearcraft:reactor_door_item>,
    <nuclearcraft:fission_block:1>,
    <nuclearcraft:buffer>,
    <nuclearcraft:active_cooler>,
    <nuclearcraft:cooler>,
    <nuclearcraft:cooler:1>,
    <nuclearcraft:cooler:2>,
    <nuclearcraft:cooler:3>,
    <nuclearcraft:cooler:4>,
    <nuclearcraft:cooler:5>,
    <nuclearcraft:cooler:6>,
    <nuclearcraft:cooler:7>,
    <nuclearcraft:cooler:8>,
    <nuclearcraft:cooler:9>,
    <nuclearcraft:cooler:10>,
    <nuclearcraft:cooler:11>,
    <nuclearcraft:cooler:12>,
    <nuclearcraft:cooler:13>,
    <nuclearcraft:cooler:14>,
    <nuclearcraft:cooler:15>,
    <nuclearcraft:dust:4>,
    <nuclearcraft:ingot_oxide>,
    <nuclearcraft:ingot_oxide:1>,
    <nuclearcraft:ingot_oxide:2>,
    <nuclearcraft:ingot_oxide:3>,
    <nuclearcraft:dust_oxide>,
    <nuclearcraft:dust_oxide:1>,
    <nuclearcraft:dust_oxide:2>,
    <nuclearcraft:dust_oxide:3>,
    <nuclearcraft:dust:3>,
    <nuclearcraft:ingot:11>,
    <nuclearcraft:ingot_block:11>,
    <nuclearcraft:compound:1>,
    <nuclearcraft:compound:2>,
    <nuclearcraft:compound:3>,
    <nuclearcraft:compound:4>,
    <nuclearcraft:compound:5>,
    <nuclearcraft:compound:6>,
    <nuclearcraft:compound:7>,
    <nuclearcraft:compound:9>,
    <nuclearcraft:compound:10>,
    <nuclearcraft:compound>,
    <nuclearcraft:gem_dust:10>,
    // Nuclearcraft Fuel Materials
    <nuclearcraft:thorium>,
    <nuclearcraft:thorium:1>,
    <nuclearcraft:thorium:2>,
    <nuclearcraft:thorium:3>,
    <nuclearcraft:thorium:4>,
    <nuclearcraft:thorium:5>,
    <nuclearcraft:thorium:6>,
    <nuclearcraft:thorium:7>,
    <nuclearcraft:neptunium>,
    <nuclearcraft:neptunium:1>,
    <nuclearcraft:neptunium:2>,
    <nuclearcraft:neptunium:3>,
    <nuclearcraft:neptunium:4>,
    <nuclearcraft:neptunium:5>,
    <nuclearcraft:neptunium:6>,
    <nuclearcraft:neptunium:7>,
    <nuclearcraft:uranium:8>,
    <nuclearcraft:uranium:9>,
    <nuclearcraft:uranium:10>,
    <nuclearcraft:uranium:11>,
    <nuclearcraft:uranium>,
    <nuclearcraft:uranium:1>,
    <nuclearcraft:uranium:2>,
    <nuclearcraft:uranium:3>,
    <nuclearcraft:uranium:4>,
    <nuclearcraft:uranium:5>,
    <nuclearcraft:uranium:6>,
    <nuclearcraft:uranium:7>,
    <nuclearcraft:americium:8>,
    <nuclearcraft:americium:9>,
    <nuclearcraft:americium:10>,
    <nuclearcraft:americium:11>,
    <nuclearcraft:plutonium>,
    <nuclearcraft:plutonium:1>,
    <nuclearcraft:plutonium:2>,
    <nuclearcraft:plutonium:3>,
    <nuclearcraft:plutonium:4>,
    <nuclearcraft:plutonium:5>,
    <nuclearcraft:plutonium:6>,
    <nuclearcraft:plutonium:7>,
    <nuclearcraft:plutonium:8>,
    <nuclearcraft:plutonium:9>,
    <nuclearcraft:plutonium:10>,
    <nuclearcraft:plutonium:11>,
    <nuclearcraft:plutonium:12>,
    <nuclearcraft:plutonium:13>,
    <nuclearcraft:plutonium:14>,
    <nuclearcraft:plutonium:15>,
    <nuclearcraft:americium>,
    <nuclearcraft:americium:1>,
    <nuclearcraft:americium:2>,
    <nuclearcraft:americium:3>,
    <nuclearcraft:americium:4>,
    <nuclearcraft:americium:5>,
    <nuclearcraft:americium:6>,
    <nuclearcraft:americium:7>,
    <nuclearcraft:californium>,
    <nuclearcraft:californium:1>,
    <nuclearcraft:californium:2>,
    <nuclearcraft:californium:3>,
    <nuclearcraft:californium:4>,
    <nuclearcraft:californium:5>,
    <nuclearcraft:californium:6>,
    <nuclearcraft:californium:7>,
    <nuclearcraft:curium>,
    <nuclearcraft:curium:1>,
    <nuclearcraft:curium:2>,
    <nuclearcraft:curium:3>,
    <nuclearcraft:curium:4>,
    <nuclearcraft:curium:5>,
    <nuclearcraft:curium:6>,
    <nuclearcraft:curium:7>,
    <nuclearcraft:curium:8>,
    <nuclearcraft:curium:9>,
    <nuclearcraft:curium:10>,
    <nuclearcraft:curium:11>,
    <nuclearcraft:curium:12>,
    <nuclearcraft:curium:13>,
    <nuclearcraft:curium:14>,
    <nuclearcraft:curium:15>,
    <nuclearcraft:berkelium>,
    <nuclearcraft:berkelium:1>,
    <nuclearcraft:berkelium:2>,
    <nuclearcraft:berkelium:3>,
    <nuclearcraft:berkelium:4>,
    <nuclearcraft:berkelium:5>,
    <nuclearcraft:berkelium:6>,
    <nuclearcraft:berkelium:7>,
    <nuclearcraft:californium:8>,
    <nuclearcraft:californium:9>,
    <nuclearcraft:californium:10>,
    <nuclearcraft:californium:11>,
    <nuclearcraft:californium:12>,
    <nuclearcraft:californium:13>,
    <nuclearcraft:californium:14>,
    <nuclearcraft:californium:15>,
    // Nuclearcraft Fuel Rods
    <nuclearcraft:fuel_americium:3>,
    <nuclearcraft:fuel_curium>,
    <nuclearcraft:fuel_curium:1>,
    <nuclearcraft:fuel_curium:2>,
    <nuclearcraft:fuel_curium:3>,
    <nuclearcraft:fuel_curium:4>,
    <nuclearcraft:fuel_curium:5>,
    <nuclearcraft:fuel_curium:6>,
    <nuclearcraft:fuel_curium:7>,
    <nuclearcraft:fuel_thorium>,
    <nuclearcraft:fuel_thorium:1>,
    <nuclearcraft:fuel_uranium>,
    <nuclearcraft:fuel_uranium:1>,
    <nuclearcraft:fuel_uranium:2>,
    <nuclearcraft:fuel_uranium:3>,
    <nuclearcraft:fuel_uranium:4>,
    <nuclearcraft:fuel_uranium:5>,
    <nuclearcraft:fuel_uranium:6>,
    <nuclearcraft:fuel_uranium:7>,
    <nuclearcraft:fuel_neptunium>,
    <nuclearcraft:fuel_neptunium:1>,
    <nuclearcraft:fuel_neptunium:2>,
    <nuclearcraft:fuel_neptunium:3>,
    <nuclearcraft:fuel_plutonium>,
    <nuclearcraft:fuel_plutonium:1>,
    <nuclearcraft:fuel_plutonium:2>,
    <nuclearcraft:fuel_plutonium:3>,
    <nuclearcraft:fuel_plutonium:4>,
    <nuclearcraft:fuel_plutonium:5>,
    <nuclearcraft:fuel_plutonium:6>,
    <nuclearcraft:fuel_plutonium:7>,
    <nuclearcraft:fuel_mixed_oxide>,
    <nuclearcraft:fuel_mixed_oxide:1>,
    <nuclearcraft:fuel_americium>,
    <nuclearcraft:fuel_americium:1>,
    <nuclearcraft:fuel_americium:2>,
    <nuclearcraft:depleted_fuel_neptunium:3>,
    <nuclearcraft:depleted_fuel_plutonium>,
    <nuclearcraft:depleted_fuel_plutonium:1>,
    <nuclearcraft:depleted_fuel_plutonium:2>,
    <nuclearcraft:depleted_fuel_plutonium:3>,
    <nuclearcraft:depleted_fuel_plutonium:4>,
    <nuclearcraft:depleted_fuel_plutonium:5>,
    <nuclearcraft:depleted_fuel_plutonium:6>,
    <nuclearcraft:depleted_fuel_plutonium:7>,
    <nuclearcraft:fuel_curium:8>,
    <nuclearcraft:fuel_curium:9>,
    <nuclearcraft:fuel_curium:10>,
    <nuclearcraft:fuel_curium:11>,
    <nuclearcraft:fuel_berkelium>,
    <nuclearcraft:fuel_berkelium:1>,
    <nuclearcraft:fuel_berkelium:2>,
    <nuclearcraft:fuel_berkelium:3>,
    <nuclearcraft:fuel_californium>,
    <nuclearcraft:fuel_californium:1>,
    <nuclearcraft:fuel_californium:4>,
    <nuclearcraft:fuel_californium:5>,
    <nuclearcraft:fuel_californium:6>,
    <nuclearcraft:fuel_californium:7>,
    <nuclearcraft:depleted_fuel_thorium>,
    <nuclearcraft:depleted_fuel_thorium:1>,
    <nuclearcraft:depleted_fuel_uranium>,
    <nuclearcraft:depleted_fuel_uranium:1>,
    <nuclearcraft:depleted_fuel_uranium:2>,
    <nuclearcraft:depleted_fuel_uranium:3>,
    <nuclearcraft:depleted_fuel_uranium:4>,
    <nuclearcraft:depleted_fuel_uranium:5>,
    <nuclearcraft:depleted_fuel_uranium:6>,
    <nuclearcraft:depleted_fuel_uranium:7>,
    <nuclearcraft:depleted_fuel_neptunium>,
    <nuclearcraft:depleted_fuel_neptunium:1>,
    <nuclearcraft:depleted_fuel_neptunium:2>,
    <nuclearcraft:depleted_fuel_californium:5>,
    <nuclearcraft:depleted_fuel_californium:6>,
    <nuclearcraft:depleted_fuel_californium:7>,
    <nuclearcraft:depleted_fuel_ic2>,
    <nuclearcraft:depleted_fuel_ic2:1>,
    <nuclearcraft:depleted_fuel_mixed_oxide>,
    <nuclearcraft:depleted_fuel_mixed_oxide:1>,
    <nuclearcraft:depleted_fuel_americium>,
    <nuclearcraft:depleted_fuel_americium:1>,
    <nuclearcraft:depleted_fuel_americium:2>,
    <nuclearcraft:depleted_fuel_americium:3>,
    <nuclearcraft:depleted_fuel_curium>,
    <nuclearcraft:depleted_fuel_curium:1>,
    <nuclearcraft:depleted_fuel_curium:2>,
    <nuclearcraft:depleted_fuel_curium:3>,
    <nuclearcraft:depleted_fuel_curium:4>,
    <nuclearcraft:depleted_fuel_curium:5>,
    <nuclearcraft:depleted_fuel_curium:6>,
    <nuclearcraft:depleted_fuel_curium:7>,
    <nuclearcraft:depleted_fuel_curium:8>,
    <nuclearcraft:depleted_fuel_curium:9>,
    <nuclearcraft:depleted_fuel_curium:10>,
    <nuclearcraft:depleted_fuel_curium:11>,
    <nuclearcraft:depleted_fuel_berkelium>,
    <nuclearcraft:depleted_fuel_berkelium:1>,
    <nuclearcraft:depleted_fuel_berkelium:2>,
    <nuclearcraft:depleted_fuel_berkelium:3>,
    <nuclearcraft:depleted_fuel_californium>,
    <nuclearcraft:depleted_fuel_californium:1>,
    <nuclearcraft:depleted_fuel_californium:2>,
    <nuclearcraft:depleted_fuel_californium:3>,
    <nuclearcraft:depleted_fuel_californium:4>,
    <nuclearcraft:fuel_californium:2>,
    <nuclearcraft:fuel_californium:3>,
    <nuclearcraft:boron>,
    <nuclearcraft:boron:1>,
    <nuclearcraft:boron:2>,
    <nuclearcraft:boron:3>,
    <nuclearcraft:lithium>,
    <nuclearcraft:lithium:1>,
    <nuclearcraft:lithium:2>,
    <nuclearcraft:lithium:3>,
    <nuclearcraft:ingot_block:8>,
    <nuclearcraft:block_depleted_neptunium>,
    <nuclearcraft:block_depleted_uranium>,
    <nuclearcraft:block_depleted_thorium>,
    <nuclearcraft:ingot_block:9>,
    <nuclearcraft:block_depleted_plutonium>,
    <nuclearcraft:block_depleted_americium>,
    <nuclearcraft:block_depleted_curium>,
    <nuclearcraft:block_depleted_berkelium>,
    <nuclearcraft:block_depleted_californium>,
    <nuclearcraft:part:1>,
    <nuclearcraft:part:2>,
    <nuclearcraft:part:3>,
    <nuclearcraft:part:5>,
    <nuclearcraft:tiny_dust_lead>,
    <nuclearcraft:block_ice>
];

for mod in stageMods {
    Recipes.setRecipeStageByMod(stage, mod);
    ItemStages.stageModItems(stage, mod);
}

for item in stageItems {
    Recipes.setRecipeStage(stage, item);
    ItemStages.addItemStage(stage, item);
}

// Recipe changes for Nuclearcraft Machines
// Keep this alphabetized. You can check out steel tech for my reaction if you don't

// Chemical Reactor
chemical_reactor.removeRecipeWithInput(<liquid:sulfur_trioxide> * 1000, <liquid:water> * 1000);

// Electrolyzer
electrolyser.removeRecipeWithInput(<liquid:water> * 500);
electrolyser.removeRecipeWithInput(<liquid:water> * 1000);
electrolyser.removeRecipeWithInput(<liquid:heavy_water> * 500);

// Remove Nuclear Furnace requirement from fission controller
recipes.remove(<nuclearcraft:fission_controller_new_fixed>);
recipes.addShaped(<nuclearcraft:fission_controller_new_fixed>, [[<nuclearcraft:part:1>, <nuclearcraft:part:5>, <nuclearcraft:part:1>],[<nuclearcraft:fission_block>, <nuclearcraft:part:10>, <nuclearcraft:fission_block>], [<nuclearcraft:part:1>, <nuclearcraft:part:5>, <nuclearcraft:part:1>]]);
